version: '3.4'

services:
  pruebaexcelformat:
    image: pruebaexcelformat:dev
    build:
      target: base
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_pruebaexcelformat$
    volumes:
      - C:\Users\bscenolasc\source\repos\PruebaExcelFormat\PruebaExcelFormat:/app
      - C:\Users\bscenolasc\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_pruebaexcelformat$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_pruebaexcelformat$ bin/Debug/netcoreapp2.2/PruebaExcelFormat.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
